name: Labels checking

on:
  label:
  workflow_dispatch:

jobs:
  check-labels:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      
      - name: Check and update labels 
        run: |
          deno run --no-check \
          --allow-read --allow-net:api.github.com --allow-env="GITHUB_TOKEN" \
          scripts/labels.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check formatting
        run: deno fmt --check